version: '3'
services:
  web:
    build:
      context: .
    container_name: server
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - "./backend:/home/app"
    ports:
      - "8080:5000"
      - "9230:9230"
    command: ["npm", "run", "debug"]