version: '3'
services:
  web:
    build:
      context: .
    container_name: server
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - "./backend:/home/app"
    ports:
      - "8080:5000"
      - "9230:9230"
    command: ["npm", "run", "debug"]
  db:
    image: mongo:4
    container_name: db
    ports:
      - "27017:27017"
  rabbitmq:
    image: bitnami/rabbitmq:3.7
    container_name: rabbitmq
    ports:
      - "15672:15672"
  mailer:
    build:
      context: .
      dockerfile: Dockerfile.mailer
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_SECURE=1
      - SMTP_USER=en57otb2vldrenmg@ethereal.email
      - SMTP_PWD=ckZWafnyfGFvqQqsHN
    volumes: 
      - "./mailer:/home/app"
    ports:
      - "9231:9230"
    command: ["npm", "run", "debug"]